#2 INTERACTIVE QUIZ

questions = {
    "Who wrote Hamlet?": "shakespeare",
    "What is the capital of France?": "Paris",
    "What is 2 + 2?": "4",
    "What is the capital of Germany?": "Berlin",
    "What is the chemical symbol for water?": "H2O",
    "Who wrote To Kill a Mockingbird?": "Harper Lee",
    "What is the capital city of Australia?": "Canberra",
    "Who painted the Mona Lisa?": "Leonardo da Vinci",
    "What is the largest planet in our solar system?": "Jupiter",
    "Which country is commonly referred to as the Land of the Rising Sun?": "Japan",
    "What is the world's longest river?": "Nile River",
    "What is the chemical symbol for the element gold?": "Au",
    "Who is known as the father of modern physics?": "Albert Einstein",
    "What is the national flower of Japan?": "Cherry blossom (Sakura)",
    "In which year did the Titanic sink?": "1912",
    "What is the national flower of the Philippines?": "Sampaguita",
    "Who wrote the novel '1984'?": "george orwell",
    "What is the largest mammal in the world?": "blue whale",
    "Which planet is known as the Red Planet?": "mars",
    "Who painted the ceiling of the Sistine Chapel?": "michelangelo",
    "What is the smallest country in the world?": "vatican city",
    "Who wrote the play 'Romeo and Juliet'?": "william shakespeare",
    "What is the tallest mountain in the world?": "mount everest",
    "What is the chemical symbol for the element silver?": "ag",
    "Which famous physicist wrote the book 'A Brief History of Time'?": "stephen hawking",
    "What is the largest continent by land area?": "asia",
    "Who was the first President of the United States?": "george washington",
    "What is the primary language spoken in Brazil?": "portuguese",
    "Which planet is known as the Morning Star or Evening Star?": "venus",
    "Who painted the famous artwork 'Starry Night'?": "vincent van gogh",
    "What is the chemical symbol for the element iron?": "fe",
    "Who wrote the novel 'Pride and Prejudice'?": "jane austen",
    "What is the longest bone in the human body?": "femur",
    "Who is often credited with inventing the telephone?": "alexander graham bell",
    "What is the largest desert in the world?": "sahara desert",
    "Which animal is known as the 'ship of the desert'?": "camel",
    "What is the chemical symbol for the element oxygen?": "o",
    "Who painted the famous artwork 'The Persistence of Memory'?": "salvador dalí",
    "What is the capital city of Italy?": "rome",
    "Which country is famous for its tulips and windmills?": "netherlands",
    "What is the chemical symbol for the element carbon?": "c",
    "What is the largest island in the world?": "greenland",
    "Who was the first man to walk on the moon?": "neil armstrong",
    "What is the national animal of Australia?": "kangaroo",
    "What is the largest species of bear?": "polar bear",
    "What is the chemical symbol for sodium?": "Na",
    "Who painted the famous artwork 'The Birth of Venus'?": "Sandro Botticelli",
    "What is the capital city of South Korea?": "Seoul",
    "Which river runs through Egypt?": "Nile River",
    "Who wrote the novel 'War and Peace'?": "Leo Tolstoy",
    "What is the chemical symbol for potassium?": "K",
    "Who discovered the theory of relativity?": "Albert Einstein",
    "What is the largest moon in the solar system?": "Ganymede",
    "Which country is known as the Land Down Under?": "Australia",
    "Who painted the famous artwork 'The Last Supper'?": "Leonardo da Vinci",
    "What is the capital city of Argentina?": "Buenos Aires",
    "Which planet is known as the Jewel of the Solar System?": "Saturn",
    "Who wrote the novel 'Jane Eyre'?": "Charlotte Brontë",
    "What is the chemical symbol for uranium?": "U",
    "Who was the first woman to fly solo across the Atlantic Ocean?": "Amelia Earhart",
    "What is the highest mountain in North America?": "Denali",
    "What is the chemical symbol for lead?": "Pb",
    "Who painted the famous artwork 'American Gothic'?": "Grant Wood",
    "What is the capital city of Egypt?": "Cairo",
    "Which country is known as the Land of the Midnight Sun?": "Norway",
    "Who wrote the novel 'The Catcher in the Rye'?": "J.D. Salinger",
    "What is the chemical symbol for tin?": "Sn",
    "Who was the first female Prime Minister of the United Kingdom?": "Margaret Thatcher",
    "What is the largest organ in the human body?": "Skin",
    "What is the chemical symbol for copper?": "Cu",
    "Who invented the World Wide Web (WWW)?": "Tim Berners-Lee",
    "What is the capital city of Germany?": "Berlin",
    "Which country is known as the Land of a Thousand Lakes?": "Finland",
    "Who wrote the novel 'The Lord of the Rings'?": "J.R.R. Tolkien",
    "What is the chemical symbol for mercury?": "Hg",
    "Who discovered the double-helix structure of DNA?": "James Watson and Francis Crick",
    "What is the capital city of Brazil?": "Brasília",
    "Which country has the largest population in the world?": "China",
    "What is the chemical symbol for calcium?": "Ca",
    "Who composed the music for the opera 'The Magic Flute'?": "Wolfgang Amadeus Mozart",
    "What is the capital city of Russia?": "Moscow",
    "Which country gifted the Statue of Liberty to the United States?": "France",
    "What is the chemical symbol for helium?": "He",
    "Who wrote the novel 'The Great Gatsby'?": "F. Scott Fitzgerald",
    "What is the highest waterfall in the world?": "Angel Falls",
    "What is the chemical symbol for phosphorus?": "P",
    "Who painted the famous artwork 'Guernica'?": "Pablo Picasso",
    "What is the capital city of India?": "New Delhi",
    "Which planet is known as the Blue Planet?": "Earth",
    "Who wrote the novel 'Don Quixote'?": "Miguel de Cervantes",
    "What is the chemical symbol for nitrogen?": "N",
    "Who discovered penicillin?": "Alexander Fleming",
    "What is the capital city of Turkey?": "Ankara",
    "Which country is known as the Land of the Thunder Dragon?": "Bhutan",
    "Who wrote the play 'Macbeth'?": "William Shakespeare",
    "What is the largest island in the Mediterranean Sea?": "Sicily",
    "What is the capital city of Thailand?": "Bangkok",
    "Who wrote the novel 'The Adventures of Huckleberry Finn'?": "Mark Twain",
    "Who painted the famous artwork 'The Thinker'?": "Auguste Rodin",
    "What is the largest lake in Africa?": "Lake Victoria"

}


def interactive_quiz():
    score = 0

    for question, answer in questions.items():
        user_answer = input(question + " ").strip().lower()
        if user_answer == answer.lower():
            score += 1
            print("Correct!")
        else:
            print(f"Wrong! The correct answer is {answer}.")

    print(f"Final score: {score}/{len(questions)}")

interactive_quiz()